### ISSUE TITLE
Please add adobe repo to your pom.xml

### ISSUE THREAD

**Issue by Strat1987** [Velir/AEM-Toolbox#3]
I was unable to install because of day-commons-gfx dependency, which is located in an adobe repo.

Please add following to your pom.xml

	<repositories>
		<repository>
		  <id>adobe</id>
		  <name>adobe repo</name>
		  <url>https://repo.adobe.com/nexus/content/groups/public</url>
		</repository>
  	</repositories>

**Comment by kairas** [comment]
Easy fix. I've pushed it in commit 65fddb4
